# Generated by Django 2.1.2 on 2018-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
